# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qEyI4vWZU_9f4xTrfNFRDULAH16pvRik
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv('/content/veriler.csv')

X = veriler.iloc[5:, 1:4]
Y = veriler.iloc[5:, 4:] # dependent
# NUMPY ARRAY DIZI DONUSUMU
x = X.values
y = Y.values

from sklearn.model_selection import train_test_split

# verinin yuzde 66 si antrenman icin kullanilsin kalan yuzde 33'u test edilsin diye ayrdik
# random_state rastsal ayirma icin kullaniliyor ayni degeri alan her kod ayni ayrimi yapar
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# burasi bir tur normalizasyon islemi anlatiyor (x-mean)/standar_deviation denklemini kullanir
X_train = sc.fit_transform(x_train)   # ogren ve ogrendiklerine gore donustur
X_test = sc.transform(x_test)         # daha once ogrendigin gibi donustur

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

mnb = MultinomialNB() # negatif data geldigi icin normalize edilmemis degerler ile kullandim
mnb.fit(x_train, y_train)

bnb = BernoulliNB()
bnb.fit(X_train, y_train)

y_predg = gnb.predict(X_test)
y_predm = mnb.predict(x_test)
y_predb = bnb.predict(X_test)

from sklearn.metrics import confusion_matrix

# satirlar y_test  | sutunlar y_pred oldu
#       e k
#     e 1 0
#     k 1 6
cmg = confusion_matrix(y_test, y_predg)
cmm = confusion_matrix(y_test, y_predm)
cmb = confusion_matrix(y_test, y_predb)

print(f'Method of Gaussian Naive Bayes\n {cmg}')
print(f'Method of Multinomial Naive Bayes\n {cmm}')
print(f'Method of Bernoulli Naive Bayes\n {cmb}')

